! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Parameters.f90
! Time                 : Wed Jul 30 15:23:53 2014
! Working directory    : /home/seastham/Dropbox (LAE)/StratCodeDev/KPP
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 185 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 175 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 139 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 10 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 538 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 176 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1745 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 2118 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 176 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 539 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 1582 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 185 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_SO4g = 1 
  INTEGER, PARAMETER :: ind_DRYACET = 2 
  INTEGER, PARAMETER :: ind_DRYCH2O = 3 
  INTEGER, PARAMETER :: ind_DRYH2O2 = 4 
  INTEGER, PARAMETER :: ind_DRYHNO3 = 5 
  INTEGER, PARAMETER :: ind_DRYN2O5 = 6 
  INTEGER, PARAMETER :: ind_DRYNO2 = 7 
  INTEGER, PARAMETER :: ind_DRYO3 = 8 
  INTEGER, PARAMETER :: ind_DRYPAN = 9 
  INTEGER, PARAMETER :: ind_DRYPMN = 10 
  INTEGER, PARAMETER :: ind_DRYPMNN = 11 
  INTEGER, PARAMETER :: ind_DRYPPN = 12 
  INTEGER, PARAMETER :: ind_DRYR4N2 = 13 
  INTEGER, PARAMETER :: ind_DRYMVK = 14 
  INTEGER, PARAMETER :: ind_DRYMACR = 15 
  INTEGER, PARAMETER :: ind_DRYHAC = 16 
  INTEGER, PARAMETER :: ind_DRYALD2 = 17 
  INTEGER, PARAMETER :: ind_SO4 = 18 
  INTEGER, PARAMETER :: ind_MSA = 19 
  INTEGER, PARAMETER :: ind_LISOPOH = 20 
  INTEGER, PARAMETER :: ind_DRYHOBr = 21 
  INTEGER, PARAMETER :: ind_DRYHBr = 22 
  INTEGER, PARAMETER :: ind_DRYBrNO3 = 23 
  INTEGER, PARAMETER :: ind_DRYBr2 = 24 
  INTEGER, PARAMETER :: ind_PYAC = 25 
  INTEGER, PARAMETER :: ind_DRYISOPND = 26 
  INTEGER, PARAMETER :: ind_DRYISOPNB = 27 
  INTEGER, PARAMETER :: ind_DRYRIP = 28 
  INTEGER, PARAMETER :: ind_DRYIEPOX = 29 
  INTEGER, PARAMETER :: ind_DRYMACRN = 30 
  INTEGER, PARAMETER :: ind_DRYMVKN = 31 
  INTEGER, PARAMETER :: ind_DRYPROPNN = 32 
  INTEGER, PARAMETER :: ind_DRYHCOOH = 33 
  INTEGER, PARAMETER :: ind_DRYACTA = 34 
  INTEGER, PARAMETER :: ind_DRYHCl = 35 
  INTEGER, PARAMETER :: ind_CO2 = 36 
  INTEGER, PARAMETER :: ind_DRYDEP = 37 
  INTEGER, PARAMETER :: ind_CH3CCl3 = 38 
  INTEGER, PARAMETER :: ind_PPN = 39 
  INTEGER, PARAMETER :: ind_BrNO2 = 40 
  INTEGER, PARAMETER :: ind_IEPOX = 41 
  INTEGER, PARAMETER :: ind_PMNN = 42 
  INTEGER, PARAMETER :: ind_CCl4 = 43 
  INTEGER, PARAMETER :: ind_CFC11 = 44 
  INTEGER, PARAMETER :: ind_CFC12 = 45 
  INTEGER, PARAMETER :: ind_CFC113 = 46 
  INTEGER, PARAMETER :: ind_CFC114 = 47 
  INTEGER, PARAMETER :: ind_CFC115 = 48 
  INTEGER, PARAMETER :: ind_H1301 = 49 
  INTEGER, PARAMETER :: ind_H2402 = 50 
  INTEGER, PARAMETER :: ind_N2O = 51 
  INTEGER, PARAMETER :: ind_H1211 = 52 
  INTEGER, PARAMETER :: ind_PAN = 53 
  INTEGER, PARAMETER :: ind_OCS = 54 
  INTEGER, PARAMETER :: ind_SO2 = 55 
  INTEGER, PARAMETER :: ind_N = 56 
  INTEGER, PARAMETER :: ind_ALK4 = 57 
  INTEGER, PARAMETER :: ind_MAP = 58 
  INTEGER, PARAMETER :: ind_CHBr3 = 59 
  INTEGER, PARAMETER :: ind_CH2Br2 = 60 
  INTEGER, PARAMETER :: ind_MPN = 61 
  INTEGER, PARAMETER :: ind_Cl2O2 = 62 
  INTEGER, PARAMETER :: ind_RA3P = 63 
  INTEGER, PARAMETER :: ind_RB3P = 64 
  INTEGER, PARAMETER :: ind_DMS = 65 
  INTEGER, PARAMETER :: ind_OClO = 66 
  INTEGER, PARAMETER :: ind_ClNO2 = 67 
  INTEGER, PARAMETER :: ind_HCFC22 = 68 
  INTEGER, PARAMETER :: ind_HCFC123 = 69 
  INTEGER, PARAMETER :: ind_HCFC141b = 70 
  INTEGER, PARAMETER :: ind_HCFC142b = 71 
  INTEGER, PARAMETER :: ind_C3H8 = 72 
  INTEGER, PARAMETER :: ind_ETP = 73 
  INTEGER, PARAMETER :: ind_HNO2 = 74 
  INTEGER, PARAMETER :: ind_CH3Br = 75 
  INTEGER, PARAMETER :: ind_CH3Cl = 76 
  INTEGER, PARAMETER :: ind_ClOO = 77 
  INTEGER, PARAMETER :: ind_MP = 78 
  INTEGER, PARAMETER :: ind_HNO4 = 79 
  INTEGER, PARAMETER :: ind_MAOP = 80 
  INTEGER, PARAMETER :: ind_BrCl = 81 
  INTEGER, PARAMETER :: ind_RP = 82 
  INTEGER, PARAMETER :: ind_Br2 = 83 
  INTEGER, PARAMETER :: ind_PP = 84 
  INTEGER, PARAMETER :: ind_ETHLN = 85 
  INTEGER, PARAMETER :: ind_MRP = 86 
  INTEGER, PARAMETER :: ind_PRPN = 87 
  INTEGER, PARAMETER :: ind_R4P = 88 
  INTEGER, PARAMETER :: ind_RIP = 89 
  INTEGER, PARAMETER :: ind_ATOOH = 90 
  INTEGER, PARAMETER :: ind_C2H6 = 91 
  INTEGER, PARAMETER :: ind_VRP = 92 
  INTEGER, PARAMETER :: ind_IAP = 93 
  INTEGER, PARAMETER :: ind_DHMOB = 94 
  INTEGER, PARAMETER :: ind_MOBA = 95 
  INTEGER, PARAMETER :: ind_N2O5 = 96 
  INTEGER, PARAMETER :: ind_INPN = 97 
  INTEGER, PARAMETER :: ind_ISNP = 98 
  INTEGER, PARAMETER :: ind_ISOPNB = 99 
  INTEGER, PARAMETER :: ind_CH4 = 100 
  INTEGER, PARAMETER :: ind_H2O2 = 101 
  INTEGER, PARAMETER :: ind_IEPOXOO = 102 
  INTEGER, PARAMETER :: ind_PMN = 103 
  INTEGER, PARAMETER :: ind_MACRNO2 = 104 
  INTEGER, PARAMETER :: ind_ROH = 105 
  INTEGER, PARAMETER :: ind_MOBAOO = 106 
  INTEGER, PARAMETER :: ind_DIBOO = 107 
  INTEGER, PARAMETER :: ind_PRPE = 108 
  INTEGER, PARAMETER :: ind_MVKN = 109 
  INTEGER, PARAMETER :: ind_H = 110 
  INTEGER, PARAMETER :: ind_BrNO3 = 111 
  INTEGER, PARAMETER :: ind_Cl2 = 112 
  INTEGER, PARAMETER :: ind_ISNOHOO = 113 
  INTEGER, PARAMETER :: ind_ISOP = 114 
  INTEGER, PARAMETER :: ind_PROPNN = 115 
  INTEGER, PARAMETER :: ind_ISNOOB = 116 
  INTEGER, PARAMETER :: ind_HOBr = 117 
  INTEGER, PARAMETER :: ind_A3O2 = 118 
  INTEGER, PARAMETER :: ind_CO = 119 
  INTEGER, PARAMETER :: ind_GLYC = 120 
  INTEGER, PARAMETER :: ind_MACRN = 121 
  INTEGER, PARAMETER :: ind_MAOPO2 = 122 
  INTEGER, PARAMETER :: ind_ISOPND = 123 
  INTEGER, PARAMETER :: ind_VRO2 = 124 
  INTEGER, PARAMETER :: ind_MRO2 = 125 
  INTEGER, PARAMETER :: ind_HC5 = 126 
  INTEGER, PARAMETER :: ind_GLYX = 127 
  INTEGER, PARAMETER :: ind_ACET = 128 
  INTEGER, PARAMETER :: ind_ISNOOA = 129 
  INTEGER, PARAMETER :: ind_MAN2 = 130 
  INTEGER, PARAMETER :: ind_PRN1 = 131 
  INTEGER, PARAMETER :: ind_PO2 = 132 
  INTEGER, PARAMETER :: ind_MGLY = 133 
  INTEGER, PARAMETER :: ind_B3O2 = 134 
  INTEGER, PARAMETER :: ind_ETO2 = 135 
  INTEGER, PARAMETER :: ind_RCO3 = 136 
  INTEGER, PARAMETER :: ind_ClNO3 = 137 
  INTEGER, PARAMETER :: ind_KO2 = 138 
  INTEGER, PARAMETER :: ind_R4N1 = 139 
  INTEGER, PARAMETER :: ind_HOCl = 140 
  INTEGER, PARAMETER :: ind_ISN1 = 141 
  INTEGER, PARAMETER :: ind_HAC = 142 
  INTEGER, PARAMETER :: ind_HNO3 = 143 
  INTEGER, PARAMETER :: ind_ATO2 = 144 
  INTEGER, PARAMETER :: ind_MVK = 145 
  INTEGER, PARAMETER :: ind_HC5OO = 146 
  INTEGER, PARAMETER :: ind_RIO2 = 147 
  INTEGER, PARAMETER :: ind_MAO3 = 148 
  INTEGER, PARAMETER :: ind_INO2 = 149 
  INTEGER, PARAMETER :: ind_MACR = 150 
  INTEGER, PARAMETER :: ind_ISOPNBO2 = 151 
  INTEGER, PARAMETER :: ind_ISOPNDO2 = 152 
  INTEGER, PARAMETER :: ind_R4O2 = 153 
  INTEGER, PARAMETER :: ind_RCHO = 154 
  INTEGER, PARAMETER :: ind_MEK = 155 
  INTEGER, PARAMETER :: ind_R4N2 = 156 
  INTEGER, PARAMETER :: ind_MCO3 = 157 
  INTEGER, PARAMETER :: ind_ALD2 = 158 
  INTEGER, PARAMETER :: ind_CH2O = 159 
  INTEGER, PARAMETER :: ind_MO2 = 160 
  INTEGER, PARAMETER :: ind_H2O = 161 
  INTEGER, PARAMETER :: ind_NO = 162 
  INTEGER, PARAMETER :: ind_NO2 = 163 
  INTEGER, PARAMETER :: ind_HO2 = 164 
  INTEGER, PARAMETER :: ind_OH = 165 
  INTEGER, PARAMETER :: ind_BrO = 166 
  INTEGER, PARAMETER :: ind_Cl = 167 
  INTEGER, PARAMETER :: ind_O = 168 
  INTEGER, PARAMETER :: ind_NO3 = 169 
  INTEGER, PARAMETER :: ind_O1D = 170 
  INTEGER, PARAMETER :: ind_Br = 171 
  INTEGER, PARAMETER :: ind_O3 = 172 
  INTEGER, PARAMETER :: ind_ClO = 173 
  INTEGER, PARAMETER :: ind_HCl = 174 
  INTEGER, PARAMETER :: ind_HBr = 175 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_ACTA = 176 
  INTEGER, PARAMETER :: ind_EMISSION = 177 
  INTEGER, PARAMETER :: ind_EOH = 178 
  INTEGER, PARAMETER :: ind_H2 = 179 
  INTEGER, PARAMETER :: ind_HCOOH = 180 
  INTEGER, PARAMETER :: ind_MOH = 181 
  INTEGER, PARAMETER :: ind_N2 = 182 
  INTEGER, PARAMETER :: ind_O2 = 183 
  INTEGER, PARAMETER :: ind_RCOOH = 184 
  INTEGER, PARAMETER :: ind_DUMMY = 185 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_ACTA = 1 
  INTEGER, PARAMETER :: indf_EMISSION = 2 
  INTEGER, PARAMETER :: indf_EOH = 3 
  INTEGER, PARAMETER :: indf_H2 = 4 
  INTEGER, PARAMETER :: indf_HCOOH = 5 
  INTEGER, PARAMETER :: indf_MOH = 6 
  INTEGER, PARAMETER :: indf_N2 = 7 
  INTEGER, PARAMETER :: indf_O2 = 8 
  INTEGER, PARAMETER :: indf_RCOOH = 9 
  INTEGER, PARAMETER :: indf_DUMMY = 10 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 864 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 2218 

END MODULE gckpp_Parameters

